"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.join(__dirname, "..");

test("Console uses one compact toolbar and hidden loading overlay cannot display", () => {
  const html = fs.readFileSync(path.join(root, "public", "index.html"), "utf8");
  const css = fs.readFileSync(path.join(root, "public", "styles.css"), "utf8");
  assert.match(html, /<header class="consolebar">/);
  assert.match(html, /<nav id="tabs" class="tabs"/);
  assert.doesNotMatch(html, /Sailing workspace/);
  assert.doesNotMatch(html, /<h1>AJRM Marine Console/);
  assert.doesNotMatch(html, /Record incident/);
  assert.doesNotMatch(html, /id="services"/);
  assert.doesNotMatch(css, /\.service-grid/);
  assert.match(css, /--console-vh:\s*100vh/);
  assert.match(css, /height:\s*var\(--console-vh\)/);
  assert.match(css, /html,\s*body\s*\{[^}]*overflow:\s*hidden;/s);
  assert.match(css, /\.consolebar\s*\{[^}]*z-index:\s*20;/s);
  assert.match(css, /#workspace\s*\{[^}]*height:\s*100%;[^}]*overflow:\s*hidden;/s);
  assert.match(css, /\.overview\s*\{[^}]*height:\s*100%;[^}]*overflow:\s*auto;/s);
  assert.match(css, /\.overview\s*\{[^}]*scrollbar-gutter:\s*stable;/s);
  assert.match(css, /\.frame-host\s*\{[^}]*overflow:\s*hidden;/s);
  assert.match(css, /\.frame-message\[hidden\]\s*\{\s*display:\s*none;/);
  assert.match(css, /grid-template-rows:\s*auto minmax\(0,\s*1fr\)/);
  assert.match(html, /id="overviewHelp"/);
  assert.match(html, /id="biteDashboard"/);
  assert.match(html, /id="biteTests"/);
  assert.match(html, /id="biteRunAll"/);
  assert.match(html, /id="biteLog"/);
  assert.match(html, /src="\.\/help\.html"/);
  assert.doesNotMatch(
    fs.readFileSync(path.join(root, "plugin", "modules.js"), "utf8"),
    /id:\s*"help"/,
  );
  assert.ok(fs.existsSync(path.join(root, "public", "help.css")));
  assert.ok(fs.existsSync(path.join(root, "public", "help.js")));
  const help = fs.readFileSync(path.join(root, "public", "help.html"), "utf8");
  assert.match(help, /AJRM Marine Help/);
  assert.match(help, /id="help-current-settings"/);
  assert.match(help, /id="help-charts"/);
  assert.doesNotMatch(help, /id="modalHelp"/);
  const helpScript = fs.readFileSync(path.join(root, "public", "help.js"), "utf8");
  assert.match(helpScript, /CPA and TCPA Limits/);
  assert.match(helpScript, /Vessel size categories/);
  assert.match(helpScript, /Harbour switching/);
});

test("Console updates viewport height for iPad Safari iframe layout", () => {
  const script = fs.readFileSync(path.join(root, "public", "app.js"), "utf8");
  assert.match(script, /function updateViewportHeight\(\)/);
  assert.match(script, /window\.innerHeight/);
  assert.match(script, /--console-vh/);
  assert.match(script, /window\.addEventListener\("resize", updateViewportHeight\)/);
  assert.match(script, /window\.addEventListener\("orientationchange"/);
});

test("Console frontend treats Logger as an ordinary selectable webapp", () => {
  const script = fs.readFileSync(path.join(root, "public", "app.js"), "utf8");
  assert.doesNotMatch(script, /toggleIncidentCapture/);
  assert.doesNotMatch(script, /incidentCapture/);
  assert.doesNotMatch(script, /AJRM Marine Logger unavailable:/);
  assert.match(script, /No webapps are selected/);
});

test("Console unloads all inactive webapp iframes and owns root browser audio", () => {
  const html = fs.readFileSync(path.join(root, "public", "index.html"), "utf8");
  const css = fs.readFileSync(path.join(root, "public", "styles.css"), "utf8");
  const script = fs.readFileSync(path.join(root, "public", "app.js"), "utf8");
  assert.match(html, /id="browserAudioHost"/);
  assert.match(html, /id="enableBrowserAudio"/);
  assert.match(script, /AUDIO_STATUS_URL/);
  assert.match(script, /AUDIO_ACCESS_TOKEN_STORAGE_KEY/);
  assert.match(script, /audioAuthHeaders/);
  assert.match(script, /BROWSER_AUDIO_AUTH_RETRY_MS/);
  assert.match(script, /nextBrowserAudioRefreshAt/);
  assert.match(script, /BROWSER_OUTPUT_MODE_STORAGE_KEY/);
  assert.match(script, /let activeFrame = null/);
  assert.match(script, /function unloadActiveFrame\(\)/);
  assert.match(script, /activeFrame\.remove\(\)/);
  assert.doesNotMatch(script, /keepAliveFrames/);
  assert.doesNotMatch(script, /dataset\.keepAlive/);
  assert.match(script, /consoleAudioHost=1/);
  assert.match(script, /function refreshBrowserAudio\(\{ force = false \} = \{\}\)/);
  assert.match(script, /BITE_STATUS_URL/);
  assert.match(script, /BITE_RUN_URL/);
  assert.match(script, /BITE_RUN_ALL_URL/);
  assert.match(script, /BITE_RUN_GROUP_URL/);
  assert.match(script, /function runBiteTest\(testId\)/);
  assert.match(script, /function runAllBiteTests\(\)/);
  assert.match(script, /function runBiteGroup\(groupId\)/);
  assert.match(script, /function biteGroupHtml\(group, allTests\)/);
  assert.match(script, /BITE_STATUS_REFRESH_MS/);
  assert.match(script, /let biteRunningTestId = null/);
  assert.match(script, /let biteRunningGroupId = null/);
  assert.match(script, /const biteExpandedGroups = new Set\(\)/);
  assert.match(script, /function startBiteStatusPolling\(\)/);
  assert.match(script, /function stopBiteStatusPolling\(\)/);
  assert.match(script, /biteStatus\.currentRunAll\?\.reports/);
  assert.match(script, /formatBiteRunAllProgress/);
  assert.match(script, /biteProgressPhrase/);
  assert.match(script, /function setBiteLog\(value\)/);
  assert.match(script, /els\.biteLog\.scrollTop = els\.biteLog\.scrollHeight/);
  assert.doesNotMatch(script, /latestReportsByTest/);
  assert.doesNotMatch(script, /biteResults\[biteStatus\.lastReport/);
  assert.match(script, /biteStatus\?\.currentRunAll\?\.currentTestId \|\| biteRunningTestId/);
  assert.match(script, /const summary = state === "disabled"/);
  assert.match(script, /test\.enabled !== false/);
  assert.match(script, /disabledReason/);
  assert.match(script, /Running BITE pre-test checks/);
  assert.match(script, /data-bite-test/);
  assert.match(script, /data-bite-group/);
  assert.match(script, /data-bite-group-toggle/);
  assert.match(script, /formatBiteReport/);
  assert.match(css, /\.bite-test\.disabled/);
  assert.match(css, /\.bite-group\.fail/);
  assert.match(css, /\.bite-group-header/);
  assert.match(script, /error\.status = response\.status/);
  assert.match(script, /status\.muted === true && announcement\.force !== true/);
  assert.match(script, /announcement\.audioUrl \|\| announcement\.publicAudioUrl/);
  assert.match(script, /function unlockBrowserAudio\(\)/);
  assert.match(script, /SILENT_AUDIO_DATA_URL/);
  assert.match(script, /function primeBrowserAudioElement/);
  assert.doesNotMatch(script, /if \(!els\.browserAudioHost\.src\) \{\s*browserAudioUnlocked = true;/);
  assert.match(script, /Enabling audio/);
  assert.match(script, /renderBrowserAudioButton/);
  assert.match(script, /firstBrowserAudioRefresh/);
  assert.match(script, /lastConsoleAnnouncementKey/);
  assert.match(script, /seenConsoleAnnouncementKeys/);
  assert.match(script, /status\.recentAnnouncements/);
  assert.match(script, /function browserAudioAnnouncements/);
  assert.match(script, /rememberConsoleAnnouncements\(announcements\)/);
  assert.match(script, /seenConsoleAnnouncementKeys\.has\(announcementKey\)/);
  assert.match(script, /function consoleAnnouncementKey/);
  assert.match(script, /if \(browserAudioUnlocked\) \{/);
});
